apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomiztion
resources:
  - deployment.yaml
  - service.yaml

namespace: goapp

images:
  - name: goapp
    newName: douglasdoro/argocd
    newTag: v1