
name: cd

on:
  push:
    branches:
      - 'main'

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output3: ${{ steps.step3.outputs.image_name }}
    steps:
      - id: step1
        run: echo "::set-output name=test::hello"
      - id: step3
        run: echo "::set-output name=image_name::$(git rev-parse --short "$GITHUB_SHA")"

  build:
    runs-on: ubuntu-latest
    needs: job1 
    # env:
    #   run: |
    #       git_hash=$(git rev-parse --short "$GITHUB_SHA")
    #       git_branch=${GITHUB_REF#refs/heads/}
    #       echo "douglasdoro/argocd:${git_hash}"
    #   # git_hash: "v1"

    
    steps:
      - 
        name: checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: show image name
        run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output3}}
        # run: |
        #   git_hash=$(git rev-parse --short "$GITHUB_SHA")
        #   git_branch=${GITHUB_REF#refs/heads/}
        #   echo "douglasdoro/argocd:${git_hash}"
        # env:
        #   IMAGE_TAG: $(git rev-parse --short "$GITHUB_SHA")
        # run: echo "douglasdoro/argocd:$GITHUB_SHA"

      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: "douglasdoro/argocd:${{ env.git_hash }}"

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - 
        name: checkout
        uses: actions/checkout@v3
      - 
        name: kustomize
        uses: imranismail/setup-kustomize@v1
      -
        name: update k8s
        run: |
          cd k8s
          kustomize edit set image goapp=douglasdoro/argocd:${GITHUB_SHA}
          cat kustomization.yaml
      - 
        name: commit
        run: |
          git add .
          git commit -m "Set `app` image tag to `${GITHUB_SHA}`"
          git push


