name: CD

on: 
  push:
    branches:
      - main
jobs:
  buid:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build image and push to docker hub
        uses: docker/build-push-action@2.10.0
        with: 
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
          repository: douglasdoro/argocd
          tags: ${{env.sha}}, latest