name: CD

on: 
  push:
    branches:
      - main
jobs:
  buid:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - 
        name: checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: build image and push to docker hu
        uses: docker/docker/build-push-action@v2
        with: 
          push: true
          repository: douglasdoro/argocd
          tags: ${{env.sha}}, latest