
name: cd

on:
  push:
    branches:
      - 'main'

jobs:
  define-image-version:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.image-version.outputs.image }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - id: image-version
        run: echo "::set-output name=image::douglasdoro/argocd:$(git rev-parse --short "$GITHUB_SHA")"

  build:
    runs-on: ubuntu-latest
    needs: define-image-version 
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{needs.define-image-version.outputs.image}}

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: [build, define-image-version] 
    steps:
      - 
        name: checkout
        uses: actions/checkout@v3
      - 
        name: kustomize
        uses: imranismail/setup-kustomize@v1
      -
        name: update k8s
        run: |
          cd k8s
          kustomize edit set image goapp=${{needs.define-image-version.outputs.image}}
          cat kustomization.yaml
      - 
        name: commit
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "Action"
          git add .
          git commit -m "Set `app` image to `${{needs.define-image-version.outputs.image}}`"
          git push


